import { UnitKey } from "@/types/global.types";

export type UnitOption = { key: string; label: string };

export const UNIT_OPTIONS: Record<UnitKey, UnitOption[]> = {
  mass: [
    { key: "g", label: "g - Gram" },
    { key: "lb", label: "lb - Pound" },
    { key: "oz", label: "oz - Ounce" },
    { key: "kg", label: "kg - Kilogram" },
    { key: "t", label: "t - Metric Ton" },
  ],
  length: [
    { key: "mm", label: "mm - Millimeter" },
    { key: "cm", label: "cm - Centimeter" },
    { key: "in", label: "in - Inch" },
    { key: "ft", label: "ft - Foot" },
    { key: "m", label: "m - Meter" },
    { key: "yd", label: "yd - Yard" },
  ],
  distance: [
    { key: "m", label: "m - Meter" },
    { key: "mi", label: "mi - Mile" },
    { key: "nmi", label: "nmi - Nautical Mile" },
    { key: "km", label: "km - Kilometer" },
  ],
  height: [
    { key: "cm", label: "cm - Centimeter" },
    { key: "in", label: "in - Inch" },
    { key: "ft", label: "ft - Foot / Inches" },
    { key: "m", label: "m - Meter" },
  ],
  area: [
    { key: "cm²", label: "cm² - Square Centimeter" },
    { key: "ft²", label: "ft² - Square Foot" },
    { key: "m²", label: "m² - Square Meter" },
    { key: "mi²", label: "mi² - Square Mile" },
    { key: "ha", label: "ha - Hectare" },
    { key: "km²", label: "km² - Square Kilometer" },
    { key: "ac", label: "ac - Acre" },
  ],
  volume: [
    { key: "t", label: "t - Metric Ton (volume)" },
    { key: "mL", label: "mL - Milliliter" },
    { key: "m³", label: "m³ - Cubic Meter" },
    { key: "L", label: "L - Liter" },
    { key: "gal", label: "gal - Gallon (US)" },
    { key: "fl oz", label: "fl oz - Fluid Ounce" },
  ],
  temperature: [
    { key: "°C", label: "°C - Celsius" },
    { key: "°F", label: "°F - Fahrenheit" },
    { key: "K", label: "K - Kelvin" },
  ],
  speed: [
    { key: "m/s", label: "m/s - Meters per Second" },
    { key: "mph", label: "mph - Miles per Hour" },
    { key: "km/h", label: "km/h - Kilometers per Hour" },
    { key: "kn", label: "kn - Knot" },
  ],
  energy: [
    { key: "kWh", label: "kWh - Kilowatt-Hour" },
    { key: "J", label: "J - Joule" },
    { key: "kJ", label: "kJ - Kilojoule" },
    { key: "BTU", label: "BTU - British Thermal Unit" },
    { key: "cal", label: "cal - Calorie" },
    { key: "kcal", label: "kcal - Kilocalorie" },
  ],
  power: [
    { key: "W", label: "W - Watt" },
    { key: "kW", label: "kW - Kilowatt" },
    { key: "MW", label: "MW - Megawatt" },
    { key: "hp", label: "hp - Horsepower" },
    { key: "BTU/h", label: "BTU/h - BTU per Hour" },
  ],
  pressure: [
    { key: "kPa", label: "kPa - Kilopascal" },
    { key: "Pa", label: "Pa - Pascal" },
    { key: "MPa", label: "MPa - Megapascal" },
    { key: "bar", label: "bar - Bar" },
    { key: "psi", label: "psi - Pound-force per Square Inch" },
    { key: "atm", label: "atm - Atmosphere" },
    { key: "mmHg", label: "mmHg - Millimeter of Mercury" },
  ],
  data: [
    { key: "KB", label: "KB - Kilobyte" },
    { key: "MB", label: "MB - Megabyte" },
    { key: "GB", label: "GB - Gigabyte" },
    { key: "TB", label: "TB - Terabyte" },
    { key: "MiB", label: "MiB - Mebibyte" },
    { key: "GiB", label: "GiB - Gibibyte" },
  ],
  dataRate: [
    { key: "Kbps", label: "Kbps - Kilobits per Second" },
    { key: "Mbps", label: "Mbps - Megabits per Second" },
    { key: "Gbps", label: "Gbps - Gigabits per Second" },
    { key: "MB/s", label: "MB/s - Megabytes per Second" },
    { key: "GB/s", label: "GB/s - Gigabytes per Second" },
  ],
  angle: [
    { key: "°", label: "° - Degree" },
    { key: "rad", label: "rad - Radian" },
    { key: "grad", label: "grad - Gradian" },
    { key: "′", label: "′ - Arcminute" },
    { key: "″", label: "″ - Arcsecond" },
  ],
};
